/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inf;

import Codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Bill extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
        
    
    public Bill() {
        initComponents();
        conn=DBconnect.connect();
        tableload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchbox = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        typebox = new javax.swing.JTextField();
        qtybox = new javax.swing.JComboBox<>();
        pricebox = new javax.swing.JTextField();
        datebox = new com.toedter.calendar.JDateChooser();
        epricebox = new javax.swing.JTextField();
        idlbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        paybtn = new javax.swing.JButton();
        clearbtn1 = new javax.swing.JButton();
        paymentbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Printing Bill");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitbtn.setBackground(new java.awt.Color(204, 255, 51));
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        backbtn.setBackground(new java.awt.Color(204, 255, 51));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        Table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 440, 340));

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 255));
        jLabel1.setText("Print Bill");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Search");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });
        jPanel1.add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 180, -1));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Price of the item");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Type");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Quentity");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("End price");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel2.add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, -1));
        jPanel2.add(typebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 190, -1));

        qtybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel2.add(qtybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 140, -1));

        pricebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceboxActionPerformed(evt);
            }
        });
        jPanel2.add(pricebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, -1));
        jPanel2.add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 140, -1));

        epricebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epriceboxActionPerformed(evt);
            }
        });
        jPanel2.add(epricebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 190, -1));

        idlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idlbl.setText("ID");
        jPanel2.add(idlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Date");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 380, 340));

        paybtn.setBackground(new java.awt.Color(204, 255, 51));
        paybtn.setText("Submit");
        paybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybtnActionPerformed(evt);
            }
        });
        jPanel1.add(paybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        clearbtn1.setBackground(new java.awt.Color(204, 255, 51));
        clearbtn1.setText("Clear");
        clearbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(clearbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        paymentbtn.setBackground(new java.awt.Color(204, 255, 51));
        paymentbtn.setText("Pay");
        paymentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentbtnActionPerformed(evt);
            }
        });
        jPanel1.add(paymentbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        Mainframe m1= new Mainframe();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void epriceboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epriceboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epriceboxActionPerformed

    private void TableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableKeyReleased
        tabledata();
    }//GEN-LAST:event_TableKeyReleased

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        tabledata();
    }//GEN-LAST:event_TableMouseClicked

    private void clearbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtn1ActionPerformed
        clear();
    }//GEN-LAST:event_clearbtn1ActionPerformed

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        search();
    }//GEN-LAST:event_searchboxKeyReleased

    private void paybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybtnActionPerformed
        int id,p = 0;
        String food;
        String type;
        String price;
        int qty;
        int eprice;
        String endprice;
        String date;
        int fprice;
        
        
        try{
                int r=Table.getSelectedRow();
                id=Integer.parseInt(Table.getValueAt(r, 3).toString());
                food=Table.getValueAt(r, 0).toString();
                type=Table.getValueAt(r, 1).toString();
                price=Table.getValueAt(r, 2).toString();
               
                switch(price){
                    case "500.0":
                        p=500;
                        break;
                        case "700.0":
                        p=700;
                        break;
                        case "550.0":
                        p=550;
                        break;
                        case "750.0":
                        p=750;
                        break;
                        case "800.0":
                        p=800;
                        break;
                        case "1250.0":
                        p=1250;
                        break;
                        case "950.0":
                        p=950;
                        break;
                        case "1750.0":
                        p=1750;
                        break;
                        case "850.0":
                        p=850;
                        break;
                        case "1600.0":
                        p=1600;
                        break;
                        
                }
                
                qty=Integer.parseInt(qtybox.getSelectedItem().toString());
                eprice=p*qty;
                endprice=String.valueOf(eprice);
                epricebox.setText(endprice);
                SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
                date=sdf.format(datebox.getDate());
                fprice=eprice;
                
            String sql="INSERT INTO bill(bid,bfood,btype,bprice,bqty,beprice,bdate,fprice) VALUES ('"+id+"','"+food+"','"+type+"','"+price+"','"+qty+"','"+eprice+"','"+date+"','"+fprice+"')";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Inserted");
            

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
       
    }//GEN-LAST:event_paybtnActionPerformed

    private void paymentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentbtnActionPerformed
        payment();
    }//GEN-LAST:event_paymentbtnActionPerformed

    private void priceboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceboxActionPerformed
public void payment(){
       Payment p1=new Payment();
       p1.setVisible(true);
       this.dispose();
}
public void tableload(){
    


             try{
                String sql="SELECT fname AS FOOD,ftype AS FOOD_TYPE,fprice AS PRICE,fid AS ID FROM food";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                Table.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
public void tabledata(){
        
        int r=Table.getSelectedRow();
        
        String food= Table.getValueAt(r, 0).toString();
        String type=  Table.getValueAt(r, 1).toString();
        String price= Table.getValueAt(r, 2).toString();
        String fid=  Table.getValueAt(r, 3).toString();
        
        namebox.setText(food);
        typebox.setText(type);
        pricebox.setText(price);
        idlbl.setText(fid);
        
                
        /*try{
                String sql="SELECT fname AS FOOD,ftype AS FOOD_TYPE,fprice AS PRICE,fid AS ID FROM food";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                
                id=rs.getInt(4);
                food2=rs.getString(1);
                type2=rs.getString(2);
                p=Integer.parseInt(rs.getString(3));
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }*/
           
    }   


 public void search(){
     
     String srh=searchbox.getText();
     
     try{
         String sql="SELECT fname AS FOOD,ftype AS FOOD_TYPE,fprice AS PRICE,fid AS ID FROM food WHERE fname LIKE'%"+srh+"%' OR fid LIKE '%"+srh+"%'";
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         Table.setModel(DbUtils.resultSetToTableModel(rs));  
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
         
     }
 }  
 public void clear(){
        
        namebox.setText("");
        typebox.setText("");
        pricebox.setText("");
        idlbl.setText("ID");
        qtybox.setSelectedIndex(0);
        epricebox.setText("");
        datebox.setDateFormatString("");
        searchbox.setText("");
        
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton clearbtn1;
    private com.toedter.calendar.JDateChooser datebox;
    private javax.swing.JTextField epricebox;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel idlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namebox;
    private javax.swing.JButton paybtn;
    private javax.swing.JButton paymentbtn;
    private javax.swing.JTextField pricebox;
    private javax.swing.JComboBox<String> qtybox;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField typebox;
    // End of variables declaration//GEN-END:variables
}
