/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inf;

import Codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    
    public Login() {
        initComponents();
        conn=DBconnect.connect();
        msg1.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        unamebox = new javax.swing.JTextField();
        userbtn = new javax.swing.JButton();
        submitbtn = new javax.swing.JButton();
        pwordbox = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        msg1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/table.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Resturant Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, 40));

        unamebox.setToolTipText("Enter user name");
        unamebox.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(unamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 190, 20));

        userbtn.setBackground(new java.awt.Color(204, 204, 204));
        userbtn.setText("Create a new user account");
        userbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnActionPerformed(evt);
            }
        });
        jPanel1.add(userbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 230, 20));

        submitbtn.setBackground(new java.awt.Color(153, 255, 0));
        submitbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("SUBMIT");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 140, 30));

        pwordbox.setToolTipText("Enter password");
        pwordbox.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        pwordbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwordboxActionPerformed(evt);
            }
        });
        jPanel1.add(pwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 190, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/log1.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        msg1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        msg1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(msg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 250, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/log2.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnActionPerformed
        Register r1=new Register();
        r1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userbtnActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        
        
        try{
        String sql="SELECT * FROM reg";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        
        String uname=unamebox.getText();
        String pword=pwordbox.getText();
      
       
        
        while(rs.next()){
        if(uname.equals(rs.getString(3)) && pword.equals(rs.getString(4))){
            
                       
            Mainframe m1=new Mainframe();
            m1.setVisible(true);
            this.dispose();
        
        }else{
            
            msg1.setVisible(true);
            msg1.setText("username or password is incorrect!");
            
          
           //JOptionPane.showMessageDialog(null,"username or password is incorrect!");
        }
        }
       }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
                }
              clear();  
                
    }//GEN-LAST:event_submitbtnActionPerformed
public void clear(){
   
    unamebox.setText("");
    pwordbox.setText("");
   
    
}    
    private void pwordboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwordboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwordboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msg1;
    private javax.swing.JPasswordField pwordbox;
    private javax.swing.JButton submitbtn;
    private javax.swing.JTextField unamebox;
    private javax.swing.JButton userbtn;
    // End of variables declaration//GEN-END:variables
}
