/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inf;

import Codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Mainframe extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;    
    
    public Mainframe() {
        initComponents();
        conn=DBconnect.connect();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contactbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        salesbtn = new javax.swing.JButton();
        staffbtn = new javax.swing.JButton();
        roombtn = new javax.swing.JButton();
        foodbtn = new javax.swing.JButton();
        tablebtn = new javax.swing.JButton();
        resevatinbtn = new javax.swing.JButton();
        billbtn = new javax.swing.JButton();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/1.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/main.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 690, 380));

        contactbtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        contactbtn.setForeground(new java.awt.Color(51, 51, 255));
        contactbtn.setText("Contact us");
        contactbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactbtnActionPerformed(evt);
            }
        });
        jPanel1.add(contactbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 120, 50));

        logoutbtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(51, 51, 255));
        logoutbtn.setText("LOG OUT");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 120, 50));

        salesbtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        salesbtn.setForeground(new java.awt.Color(51, 51, 255));
        salesbtn.setText("Total Sales");
        salesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesbtnActionPerformed(evt);
            }
        });
        jPanel1.add(salesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 120, 50));

        staffbtn.setBackground(new java.awt.Color(255, 255, 153));
        staffbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/1.png"))); // NOI18N
        staffbtn.setToolTipText("Staff");
        staffbtn.setBorder(null);
        staffbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffbtnActionPerformed(evt);
            }
        });
        jPanel1.add(staffbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 110));

        roombtn.setBackground(new java.awt.Color(255, 255, 153));
        roombtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/2.png"))); // NOI18N
        roombtn.setToolTipText("Rooms");
        roombtn.setBorder(null);
        roombtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roombtnActionPerformed(evt);
            }
        });
        jPanel1.add(roombtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 130, 110));

        foodbtn.setBackground(new java.awt.Color(255, 255, 153));
        foodbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/5.png"))); // NOI18N
        foodbtn.setToolTipText("Food Menu");
        foodbtn.setBorder(null);
        foodbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodbtnActionPerformed(evt);
            }
        });
        jPanel1.add(foodbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 110));

        tablebtn.setBackground(new java.awt.Color(255, 255, 153));
        tablebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/3.png"))); // NOI18N
        tablebtn.setToolTipText("Table Reserved");
        tablebtn.setBorder(null);
        tablebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablebtnActionPerformed(evt);
            }
        });
        jPanel1.add(tablebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 130, 110));

        resevatinbtn.setBackground(new java.awt.Color(255, 255, 153));
        resevatinbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/4.png"))); // NOI18N
        resevatinbtn.setToolTipText("Today Reservations");
        resevatinbtn.setBorder(null);
        resevatinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resevatinbtnActionPerformed(evt);
            }
        });
        jPanel1.add(resevatinbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 120, 110));

        billbtn.setBackground(new java.awt.Color(255, 255, 153));
        billbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/6.png"))); // NOI18N
        billbtn.setToolTipText("Print Bill");
        billbtn.setBorder(null);
        billbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billbtnActionPerformed(evt);
            }
        });
        jPanel1.add(billbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 130, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resevatinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resevatinbtnActionPerformed
        Reservation r2=new Reservation();
        r2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resevatinbtnActionPerformed

    private void tablebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablebtnActionPerformed
        Table t1=new Table();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tablebtnActionPerformed

    private void roombtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roombtnActionPerformed
        Room r1=new Room();
        r1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_roombtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
       System.exit(0);
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void foodbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodbtnActionPerformed
        
        Food f1=new Food();
        f1.setVisible(true);
        this.dispose();
        delete();
    }//GEN-LAST:event_foodbtnActionPerformed

    private void staffbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffbtnActionPerformed
       
        Staff f1=new Staff();
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_staffbtnActionPerformed

    private void billbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billbtnActionPerformed
        Bill b1=new Bill();
        b1.setVisible(true);
        this.dispose();
        delete2();
    }//GEN-LAST:event_billbtnActionPerformed

    private void salesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesbtnActionPerformed
        AdminLogin a1=new AdminLogin();
        a1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salesbtnActionPerformed

    private void contactbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactbtnActionPerformed
       Contact c1=new Contact();
       c1.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_contactbtnActionPerformed
   public void delete(){
   
  
            try{
                String sql="DELETE FROM food";
                pst=conn.prepareStatement(sql);
                pst.execute();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
} 
}
   public void delete2(){
   
  
            try{
                String sql="DELETE FROM bill";
                pst=conn.prepareStatement(sql);
                pst.execute();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
} 
}
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billbtn;
    private javax.swing.JButton contactbtn;
    private javax.swing.JButton foodbtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton resevatinbtn;
    private javax.swing.JButton roombtn;
    private javax.swing.JButton salesbtn;
    private javax.swing.JButton staffbtn;
    private javax.swing.JButton tablebtn;
    // End of variables declaration//GEN-END:variables
}
