/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inf;

import Codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Payment extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public Payment() {
        initComponents();
        conn=DBconnect.connect();
       
        tableload();
        calculate();
        delete();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        searchbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        calbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        visabtn = new javax.swing.JButton();
        ambtn = new javax.swing.JButton();
        msbtn = new javax.swing.JButton();
        mwal = new javax.swing.JButton();
        gwal = new javax.swing.JButton();
        boc = new javax.swing.JButton();
        hnb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment option");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        Table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 380, 290));

        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        jPanel1.add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 130, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Displaying your Items......");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Total Amount of your Items prices......");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        calbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calboxActionPerformed(evt);
            }
        });
        jPanel1.add(calbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 190, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Search");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Payment Option");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Credit/Debit Card");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Internet Banking");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Mobile Wallet");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        visabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/card.jpg"))); // NOI18N
        visabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visabtnActionPerformed(evt);
            }
        });
        jPanel2.add(visabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, 40));

        ambtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/card3.jpg"))); // NOI18N
        ambtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambtnActionPerformed(evt);
            }
        });
        jPanel2.add(ambtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 80, 40));

        msbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/card2.jpg"))); // NOI18N
        msbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msbtnActionPerformed(evt);
            }
        });
        jPanel2.add(msbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 70, 40));

        mwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/card4.png"))); // NOI18N
        jPanel2.add(mwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 30));

        gwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/card5.jpg"))); // NOI18N
        jPanel2.add(gwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 50, 30));

        boc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/card6.png"))); // NOI18N
        jPanel2.add(boc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 60, 40));

        hnb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/card7.png"))); // NOI18N
        jPanel2.add(hnb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 60, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 310, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void calboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calboxActionPerformed

    private void TableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableKeyReleased
            
    }//GEN-LAST:event_TableKeyReleased

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
            
    }//GEN-LAST:event_TableMouseClicked

    private void visabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visabtnActionPerformed
        Card c1=new Card();
        c1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_visabtnActionPerformed

    private void ambtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambtnActionPerformed
        Card c1=new Card();
        c1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ambtnActionPerformed

    private void msbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msbtnActionPerformed
        Card c1=new Card();
        c1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_msbtnActionPerformed
public void tableload(){
    


             try{
                String sql="SELECT bid AS ID,bfood AS Food,btype AS TYPE,bprice AS Price,bqty AS Qty,beprice AS End_price,bdate AS Date FROM bill";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                Table.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
public void calculate(){
    
    try{
        String sql="SELECT sum(fprice) FROM bill";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
            String total=rs.getString("sum(fprice)");
            
            calbox.setText(total);
            
            JOptionPane.showMessageDialog(null," KDSL GROUP \n Your total amount is Rs."+total+ "\n PAY AND TAKE YOUR FOODS");

            
        }   
    }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    
    total();
}

public void total(){
    
    int total;
    
    try{
        
       total=Integer.parseInt(calbox.getText());
       
       String sql="INSERT INTO total(eprice) VALUES('"+total+"')";
       pst=conn.prepareStatement(sql);
       pst.execute();
               
    }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }       
               
    
}
 public void delete(){
        
         try{
                String sql="DELETE FROM amo";
                pst=conn.prepareStatement(sql);
                pst.execute();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
} 
 }
/*public void delete(){
    
    
    int r=Table.getSelectedRow();
    int id=Integer.parseInt(Table.getValueAt(r, 3).toString());
  
            try{
                String sql="DELETE FROM bill WHERE bid='"+id+"'";
                pst=conn.prepareStatement(sql);
                pst.execute();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
}    
}*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton ambtn;
    private javax.swing.JButton boc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField calbox;
    private javax.swing.JButton gwal;
    private javax.swing.JButton hnb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton msbtn;
    private javax.swing.JButton mwal;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton visabtn;
    // End of variables declaration//GEN-END:variables
}
