/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inf;


import Codes.DBconnect;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Receipt extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
   
    
    
    public Receipt() {
        initComponents();
        conn=DBconnect.connect();
        
        
        tableload();
        calculate();
        balance();
        change();
       
       //cashlbl.setText(Integer.toString(a));
        
    }
    
    

    /*public void amount(int a) {
        
     
        cashlbl.setText(Integer.toString(a));
        
    }*/
    
   
    
    public void tableload(){
    


             try{
                String sql="SELECT bfood AS Food,btype AS TYPE,bprice AS Price,bqty AS Qty,beprice AS End_price,bdate AS Date FROM bill";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                Table.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    public void calculate(){
    
       
    try{
        String sql="SELECT sum(fprice) FROM bill";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
            int total=rs.getInt("sum(fprice)");
            
            
            totlbl.setText(Integer.toString(total));
        }
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
   
    
    }
    
    public void balance(){
        
       
        
        try{
                String sql="SELECT * FROM amo";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                
                if(rs.next()){
                int amount=rs.getInt("amount");
                
                cashlbl.setText(Integer.toString(amount));
                
                }

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }
    public void change(){
        
        int change = 0;
        int amount = Integer.parseInt(cashlbl.getText());
        int total = Integer.parseInt(totlbl.getText());
        
        change=amount-total; 
        chalbl.setText(Integer.toString(change));
    }    
         
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totlbl = new javax.swing.JLabel();
        cashlbl = new javax.swing.JLabel();
        chalbl = new javax.swing.JLabel();
        totlbl1 = new javax.swing.JLabel();
        cashlbl1 = new javax.swing.JLabel();
        chalbl1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        printbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receipt");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("KDSL GROUP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("--------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 720, 600, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("071 373 1530 / 077 316 9720");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("THANK YOU!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("--------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 600, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("--------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 600, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("CHANGE :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("TOTAL AMOUNT  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("CASH :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        totlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totlbl.setText("00.00");
        jPanel1.add(totlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        cashlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cashlbl.setText("00.00");
        jPanel1.add(cashlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, -1));

        chalbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chalbl.setText("00.00");
        jPanel1.add(chalbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, -1, -1));

        totlbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totlbl1.setText("Rs.");
        jPanel1.add(totlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, -1, -1));

        cashlbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cashlbl1.setText("Rs.");
        jPanel1.add(cashlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, -1, -1));

        chalbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chalbl1.setText("Rs.");
        jPanel1.add(chalbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("--------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 600, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("NO 10, Kandy Road, Kegalle");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/barcode.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("--------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 600, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/icon.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 50, 50));

        jLabel15.setFont(new java.awt.Font("Vivaldi", 1, 20)); // NOI18N
        jLabel15.setText("Come Again....");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 700, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/bar.jpg"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 590, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 670, 750));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printbtn.setBackground(new java.awt.Color(153, 255, 0));
        printbtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        printbtn.setForeground(new java.awt.Color(255, 255, 255));
        printbtn.setText("PRINT");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        jPanel2.add(printbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 10, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
       
    PrinterJob pj = PrinterJob.getPrinterJob();
    pj.setJobName(" Print Component ");

    pj.setPrintable (new Printable() {    
    public int print(Graphics pg, PageFormat pf, int pageNum){
       pf.setOrientation(PageFormat.PORTRAIT);
      if (pageNum > 0){
      return Printable.NO_SUCH_PAGE;
      }

      Graphics2D g2 = (Graphics2D) pg;
      g2.translate(pf.getImageableX(), pf.getImageableY());
      g2.scale(0.63,0.97);
      jPanel1.paint(g2);
      return Printable.PAGE_EXISTS;
    }
    });
    if (pj.printDialog() == false)
    return;

    try {
        pj.print();
    } catch (PrinterException ex) {
        // handle exception
    }
    }//GEN-LAST:event_printbtnActionPerformed
    
    

       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JLabel cashlbl;
    private javax.swing.JLabel cashlbl1;
    private javax.swing.JLabel chalbl;
    private javax.swing.JLabel chalbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printbtn;
    private javax.swing.JLabel totlbl;
    private javax.swing.JLabel totlbl1;
    // End of variables declaration//GEN-END:variables
}
