/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inf;

import Codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Reservation extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public Reservation() {
        initComponents();
        conn=DBconnect.connect();
         tableload1();
         tableload2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        exitbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchbox2 = new javax.swing.JTextField();
        searchbox1 = new javax.swing.JTextField();
        searchbox3 = new javax.swing.JTextField();
        searchbox4 = new javax.swing.JTextField();
        searchbox5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/resevation.jpg"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(204, 255, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/resevation.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Today Reservations");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Today Table Booking");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Today Room Booking");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        Table2.setBackground(new java.awt.Color(102, 255, 255));
        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table2.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(Table2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 360, 220));

        Table1.setBackground(new java.awt.Color(102, 255, 255));
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Table1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 360, 220));

        exitbtn.setBackground(new java.awt.Color(204, 255, 51));
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        backbtn.setBackground(new java.awt.Color(204, 255, 51));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Table Booking");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Room Service");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        searchbox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbox2KeyReleased(evt);
            }
        });
        jPanel1.add(searchbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 220, -1));

        searchbox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbox1KeyReleased(evt);
            }
        });
        jPanel1.add(searchbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 220, -1));

        searchbox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbox3KeyReleased(evt);
            }
        });
        jPanel1.add(searchbox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 220, -1));

        searchbox4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbox4KeyReleased(evt);
            }
        });
        jPanel1.add(searchbox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 220, -1));

        searchbox5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbox5KeyReleased(evt);
            }
        });
        jPanel1.add(searchbox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 220, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inf/resevation.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        
        Mainframe m1= new Mainframe();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
       
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void searchbox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbox1KeyReleased
        search1();
    }//GEN-LAST:event_searchbox1KeyReleased

    private void searchbox2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbox2KeyReleased
        search2();
    }//GEN-LAST:event_searchbox2KeyReleased

    private void searchbox3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbox3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbox3KeyReleased

    private void searchbox4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbox4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbox4KeyReleased

    private void searchbox5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbox5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbox5KeyReleased
public void tableload1(){
    


             try{
                String sql="SELECT rrnumber AS Room_no,avb AS Availability FROM room";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                Table1.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
                

            
public void tableload2(){

            try{
                String sql="SELECT tnumber AS Table_no,avb AS Availability FROM tab";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                Table2.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
public void search1(){
     
     String srh=searchbox1.getText();
     
     try{
         String sql="SELECT rrnumber AS Room_no,avb AS Availability FROM room WHERE rrnumber LIKE'%"+srh+"%'";
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         Table1.setModel(DbUtils.resultSetToTableModel(rs));  
     }
     catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
         
     }
}
public void search2(){
     
     String srh=searchbox2.getText();
     
     try{
         String sql="SELECT tnumber AS Table_no,avb AS Availability FROM tab WHERE tnumber LIKE'%"+srh+"%'";
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         Table2.setModel(DbUtils.resultSetToTableModel(rs));  
     }
     catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
         
     }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JTable Table2;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField searchbox1;
    private javax.swing.JTextField searchbox2;
    private javax.swing.JTextField searchbox3;
    private javax.swing.JTextField searchbox4;
    private javax.swing.JTextField searchbox5;
    // End of variables declaration//GEN-END:variables
}
