/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inf;

import Codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Staff extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public Staff() {
        initComponents();
         conn=DBconnect.connect();
         tableload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sectionbox = new javax.swing.JTextField();
        namebox = new javax.swing.JTextField();
        pnumberbox = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        addressbox = new javax.swing.JTextField();
        agebox = new javax.swing.JTextField();
        idbox = new javax.swing.JTextField();
        datebox = new com.toedter.calendar.JDateChooser();
        positionbox = new javax.swing.JComboBox<>();
        exitbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        insertbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        searchbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        idlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff");

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Staff");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 70, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Name");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Position");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Phone Number");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Section");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Address");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Age");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("ID Number");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Job started date");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        jPanel2.add(sectionbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, -1));
        jPanel2.add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, -1));
        jPanel2.add(pnumberbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 170, -1));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, -1));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 170, -1));

        addressbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressboxActionPerformed(evt);
            }
        });
        jPanel2.add(addressbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 170, -1));
        jPanel2.add(agebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 170, -1));
        jPanel2.add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 170, -1));

        datebox.setDateFormatString("yy-MM-dd");
        jPanel2.add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 170, -1));

        positionbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receptionist", "Waiter", "Cook", "Chef", "Room attendant", "Accountant", "Bell boy", "Delivery driver", "Cashier", "Security Guard", "Doorman", "Manager" }));
        positionbox.setToolTipText("Select");
        jPanel2.add(positionbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 310, 360));

        exitbtn.setBackground(new java.awt.Color(204, 255, 51));
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        backbtn.setBackground(new java.awt.Color(204, 255, 51));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        insertbtn.setBackground(new java.awt.Color(204, 255, 51));
        insertbtn.setText("INSERT");
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });
        jPanel1.add(insertbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        updatebtn.setBackground(new java.awt.Color(204, 255, 51));
        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        deletebtn.setBackground(new java.awt.Color(204, 255, 51));
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel1.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        clearbtn.setBackground(new java.awt.Color(204, 255, 51));
        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        searchbox.setToolTipText("Search");
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });
        jPanel1.add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 120, -1));

        Table.setBackground(new java.awt.Color(204, 204, 204));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        Table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 480, 400));

        idlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idlbl.setText("ID");
        jPanel1.add(idlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        
        Mainframe m1=new Mainframe();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed

        String name;
        String pnumber;
        String position;
        String section;
        String address;
        int age;
        String nic;
        String date;
        int id;
        
        try{
            
        name=namebox.getText();
        pnumber=pnumberbox.getText();
        position=positionbox.getSelectedItem().toString();
        //section=sectionbox.getText();
        address=addressbox.getText();
        age=Integer.parseInt(agebox.getText());
        nic=idbox.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        date=sdf.format(datebox.getDate());
        
        if(position=="Receptionist" || position=="Cashier"|| position=="Doorman"|| position=="Bell boy"){
            
            
                 
            section="Front Office";
            sectionbox.setText(section);
        }
        else if(position=="Room attendant"){
            
            section="Housekeping";
            sectionbox.setText(section);                      
        }
         else if(position=="Waiter"|| position=="Delivery driver"){
            
            section="Food And Beverage";
            sectionbox.setText(section);                      
        }
        else if(position=="Cook"|| position=="Chef"){
            
            section="Kitchen Or Food";
            sectionbox.setText(section);                      
        }
        else if(position=="Manager"){
            
            section="Management";
            sectionbox.setText(section);                      
        }
        else if(position=="Accountant"){
            
            section="Fainance";
            sectionbox.setText(section);                      
        }
        else{
            section="Security Guard";
            sectionbox.setText(section);  
        }

        
            String sql="INSERT INTO stf(sname,sphone,sposition,ssection,saddress,sage,snic,sdate) VALUES ('"+name+"','"+pnumber+"','"+position+"','"+section+"','"+address+"','"+age+"','"+nic+"','"+date+"')";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Inserted");
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, "Enter correct value!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        tableload();
        }

        public void tableload(){

            try{
                String sql="SELECT sname AS Name,sphone AS Phone_no,sposition AS Position,ssection AS Section,saddress AS Address,sage AS Age,snic AS NIC,sdate AS Date,sid AS ID FROM stf";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                Table.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }

        public void tabledata(){

            int r=Table.getSelectedRow();

            String name= Table.getValueAt(r, 0).toString();
            String pnumber=  Table.getValueAt(r, 1).toString();
            String position= Table.getValueAt(r, 2).toString();
            String section=  Table.getValueAt(r, 3).toString();
            String address=  Table.getValueAt(r, 4).toString();
            String age=  Table.getValueAt(r, 5).toString();
            String nic=  Table.getValueAt(r, 6).toString();
            String date=  Table.getValueAt(r, 7).toString();
            String id=  Table.getValueAt(r, 8).toString();


            namebox.setText(name);
            pnumberbox.setText(pnumber);
            positionbox.setSelectedItem(position);
            sectionbox.setText(section);
            addressbox.setText(address);
            agebox.setText(age);
            idbox.setText(nic);
            datebox.setDateFormatString(date);
            idlbl.setText(id);
            

    }//GEN-LAST:event_insertbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        update();
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        int check=JOptionPane.showConfirmDialog(null, "Do you want to delete!");

        if(check==0){

            String id=idlbl.getText();

            try{
                String sql="DELETE FROM stf WHERE sid='"+id+"'";
                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

        }
        tableload();
        clear();
    }//GEN-LAST:event_deletebtnActionPerformed
public void search(){
     
     String srh=searchbox.getText();
     
     try{
         String sql="SELECT sname AS Name,sphone AS Phone_no,sposition AS Position,ssection AS Section,saddress AS Address,sage AS Age,snic AS NIC,sdate AS Date,sid AS ID FROM stf WHERE sname LIKE'%"+srh+"%' OR sid LIKE '%"+srh+"%'";
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         Table.setModel(DbUtils.resultSetToTableModel(rs));  
     }
     catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
         
     }
}
     public void update(){
         
     
        String name=namebox.getText();
        String pnumber=pnumberbox.getText();
        String position=positionbox.getSelectedItem().toString();
        String section;
        String address=addressbox.getText();
        String age=agebox.getText();
        String nic=idbox.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        String date = sdf.format(datebox.getDate());
        String id=idlbl.getText();
        
        if(position=="Receptionist" || position=="Cashier"|| position=="Doorman"|| position=="Bell boy"){
            
            
            section="Front Office";
            sectionbox.setText(section);
        }
        else if(position=="Room attendant"){
            
            section="Housekeping";
            sectionbox.setText(section);                      
        }
         else if(position=="Waiter"|| position=="Delivery driver"){
            
            section="Food And Beverage";
            sectionbox.setText(section);                      
        }
        else if(position=="Cook"|| position=="Chef"){
            
            section="Kitchen Or Food";
            sectionbox.setText(section);                      
        }
        else if(position=="Manager"){
            
            section="Management";
            sectionbox.setText(section);                      
        }
        else if(position=="Accountant"){
            
            section="Fainance";
            sectionbox.setText(section);                      
        }
        else{
            section="Security Guard";
            sectionbox.setText(section);  
        }
        
        
         try{
        String sql="UPDATE stf SET sname='"+name+"',sphone='"+pnumber+"',sposition='"+position+"',ssection='"+section+"',saddress='"+address+"',sage='"+age+"',snic='"+nic+"',sdate='"+date+"' WHERE sid='"+id+"'";
        pst=conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Updated");
    }   catch(RuntimeException e){
            JOptionPane.showMessageDialog(null, "Enter correct value!");
        }
         catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
    }
        
    tableload();
     }
     
     public void clear(){
         
            namebox.setText("");
            pnumberbox.setText("");
            positionbox.setSelectedIndex(0);
            sectionbox.setText("");
            addressbox.setText("");
            agebox.setText("");
            idbox.setText("");
            datebox.setDateFormatString("");
            idlbl.setText("ID");
            searchbox.setText("");
     }
     
    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clear();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        search();
    }//GEN-LAST:event_searchboxKeyReleased

    private void addressboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressboxActionPerformed

    private void TableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableKeyReleased
        tabledata();
    }//GEN-LAST:event_TableKeyReleased

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
       tabledata();
    }//GEN-LAST:event_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField addressbox;
    private javax.swing.JTextField agebox;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton clearbtn;
    private com.toedter.calendar.JDateChooser datebox;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField idbox;
    private javax.swing.JLabel idlbl;
    private javax.swing.JButton insertbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField pnumberbox;
    private javax.swing.JComboBox<String> positionbox;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField sectionbox;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
